<!-- Factorar código -->

<?php 
	function cabeceraPage()
	{
?>
	<TABLE WIDTH=102% CELLSPACING=0>
	<TD BACKGROUND="../images/top1a.jpg" HEIGHT=44 VALIGN=BOTTOM>
	<!--inserta dentro de la imagen-->
	   <TABLE HEIGHT=26>
	   <TD WIDTH=510>
	   <TD VALIGN=TOP>
	   <FONT SIZE=1 COLOR=CACACA><B>UMSS</b></font>
	   </TABLE>

	<TR>
	<TD BACKGROUND="../images/top2a.jpg" HEIGHT=133 VALIGN=TOP>
	   <TABLE CELLPADDING=8>
		 <TD height="71"><font color="FFFFFF" size="8">CARRERA DE TURISMO</font>
	   </TABLE>
	   <TR>
	<TD height="26">

<?php
	}
	
	function piePage()
	{
?>

	<TR>
	<TR>
	<TD BACKGROUND="../images/bottom.jpg" HEIGHT=70>

	<table border="0" cellpadding="0" cellspacing="0" width="100%" height="57">
	  <tr>
		<td width="100%" height="1">UMSS</td>
	  </tr>
	</table>
	<p>
		<CENTER>
			<FONT SIZE=1 COLOR=CCCCCC>
			Facultad de Arquitectura </font>
	   </CENTER>

	</TABLE>

	<div style="text-align: center; font-size: 0.75em;">-----EV-----</div>
<?php
	}
?>
	